### ISSUE TITLE
Error While Stopping the node.

### ISSUE THREAD

**Issue by finnyfound** [Joystream/substrate-node-joystream#73]
I usually restart the node by Closing the current session using `Control +C` and restarting backup right then.
This time i got this error.
I am running as a validator on a storage node, which i stopped before restarting the validator.
I had added extra tags while running them `--in-peers 200 --out-peers 200`

```
        https://www.joystream.org/


====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::ha884f93dfb025b50 (0x5619ac12deaf)
   1: rust_panic_with_hook (0x5619ac276528)
             at src/libstd/panicking.rs:482
   2: std::panicking::begin_panic::hdf4e3b10bbf76e2a (0x5619abf38334)
   3: <slog_scope::NoGlobalLoggerSet as slog::Drain>::log::ha80ee0103e08b81c (0x5619abf37b48)
   4: <std::thread::local::LocalKey<T>>::with::h852861ce912983e6 (0x5619ab518e0e)
   5: <substrate_finality_grandpa::GossipValidator<Block> as substrate_network::consensus_gossip::Validator<<Block as sr_primitives::traits::Block>::Hash>>::validate::h13389836331a3ba5 (0x5619ab6d858f)
   6: <substrate_network::consensus_gossip::ConsensusGossip<B>>::on_incoming::hb862d6cde8a2f62f (0x5619ab7115ba)
   7: <substrate_network::protocol::Protocol<B, S, H>>::on_custom_message::h5ab0a237e719c3d7 (0x5619ab87c382)
   8: <substrate_network::protocol::Protocol<B, S, H>>::handle_msg::hbfac70847cf9f4cd (0x5619ab876c29)
   9: <substrate_network::protocol::Protocol<B, S, H>>::run::hfbc9120e11903f9d (0x5619ab884349)
  10: std::sys_common::backtrace::__rust_begin_short_backtrace::h57cf56508ab931eb (0x5619ab6f4bd0)
  11: std::panicking::try::do_call::hddc750f86d594733 (0x5619ab55a5e3)
  12: __rust_maybe_catch_panic (0x5619ac27c739)
             at src/libpanic_unwind/lib.rs:87
  13: <F as alloc::boxed::FnBox<A>>::call_box::h46cead66f572be07 (0x5619ab7ea877)
  14: call_once<(),()> (0x5619ac27ba7d)
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/liballoc/boxed.rs:759
      start_thread
             at src/libstd/sys_common/thread.rs:14
      thread_start
             at src/libstd/sys/unix/thread.rs:81
  15: start_thread (0x7fa0f07296da)
  16: __clone (0x7fa0f023a88e)
  17: <unknown> (0x0)

Thread 'Protocol' panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.1.1/lib.rs:123

This is a bug. Please report it at:

        https://www.joystream.org/
```

The controller address for the said validator is the following `5EZMa6jf1rDfBTkE2zcGnBc5b6jDhJAfRyaGdp4ERZaL98RK`
Hope it helps.

**Comment by mnaamani** [comment]
Thanks for reporting this.
Did you get the error during shutdown or startup?

**Comment by finnyfound** [comment]
During Shutdown

**Comment by bwhm** [comment]
Did it start back up without any issues?

**Comment by finnyfound** [comment]
Yes i was able to start it without any issues.

**Comment by mnaamani** [comment]
This issue is with reference to an older version of the node that is outdated and no longer in production.
Closing.
